-- SQL Schema for Inkwell Supabase Integration
-- Run this in your Supabase SQL Editor

-- 1. Profiles Table (syncs with auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  avatar_url text,
  username text unique,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. Articles Table
create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  tagline text,
  category text,
  cover_image text,
  body text,
  author_id uuid references public.profiles(id),
  author_name text,
  pub_date text,
  likes_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.articles enable row level security;

create policy "Articles are viewable by everyone."
  on articles for select
  using ( true );

-- 3. Comments Table
create table public.comments (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  user_name text,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.comments enable row level security;

create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

create policy "Authenticated users can post comments."
  on comments for insert
  with check ( auth.role() = 'authenticated' );

-- 4. Conversations & Messages (Real-time Chat)
create table public.conversations (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.conversation_participants (
  conversation_id uuid references public.conversations(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  primary key (conversation_id, user_id)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.conversations(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.messages enable row level security;

create policy "Users can view messages in their conversations."
  on messages for select
  using (
    exists (
      select 1 from conversation_participants
      where conversation_id = messages.conversation_id
      and user_id = auth.uid()
    )
  );

create policy "Users can send messages to their conversations."
  on messages for insert
  with check (
    exists (
      select 1 from conversation_participants
      where conversation_id = messages.conversation_id
      and user_id = auth.uid()
    )
  );

-- Function to handle new user signup and create a profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, username)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email);
  return new;
end;
$$ language plpgsql security modeller;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
